# Generated by cucumber-sinatra. (Wed Apr 27 17:50:54 +0200 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'application.rb')

require 'capybara'
require 'capybara-webkit'
require 'capybara/cucumber'
require 'rspec'
#require 'database_cleaner'
#require 'database_cleaner/cucumber'

Capybara.app = Sinatra::Application

Capybara.javascript_driver = :webkit

class GeoReviewWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  GeoReviewWorld.new
end
